---
title: "Olvera_yr1Exam"
author: "Jocelyn Olvera/PID:A12459601"
date: "7/18/2022"
output: pdf_document
---
### Import packages to be used in plotting COVID-19 data. 
```{r "setup, include=FALSE"}
library(ggplot2)
library(dplyr)
```

### Read in csv file and inspect the first few lines. 
```{r}
# Read in csv 
covid <- read.csv("../Bioinformatics_yr1_Exam/covid19_variants.csv")

# Inspect first 6 lines of the data
head(covid)
```


# Remove columns with NA values. 
```{r}
covid <- select(covid, -specimens_7d_avg, -percentage_7d_avg)
head(covid)
```

# Remove row that are not individual variants ("Other" and "Total") 
```{r} 
covid19 <- covid %>%
  filter(variant_name !="Other") %>% filter(variant_name !="Total")
head(covid19)
```

### Generating graph using ggplot
```{r}
library(ggthemr)
ggthemr("dust")

ggplot(covid19, aes(x=as.Date(date), y=percentage, group=variant_name, col=variant_name))+ 
    theme_light() + # light minimal background
    geom_line(size=0.7) + # making lines thicker
    ggtitle("COVID-19 Variants in California") + # setting title
    theme(plot.title = element_text(hjust = 0.5)) +
    ylab("Percentage of Sequenced Specimens") + # Renaming the Y axis
    xlab("Month and Year") + #Renaming the X axis
    scale_x_date(date_labels= "%m %Y", date_breaks = "1 month") + #labeling by month number and year
    theme(axis.text.x = element_text(angle=45, hjust=0.8)) # angle text for and adjust height to avoid overlap with graph. 

```
